# Generated by Django 4.1.1 on 2023-04-03 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nom du produit')),
                ('price', models.FloatField(verbose_name='Prix du produit')),
                ('description', models.TextField(null=True, verbose_name='Description du produit')),
                ('is_subscription', models.BooleanField(default=False, verbose_name='Abonnement')),
                ('classes_remaining', models.IntegerField(default=10, verbose_name='Nombre de cours restants')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
