# Generated by Django 4.1.1 on 2022-09-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='finished',
        ),
    ]
