# Generated by Django 4.1.1 on 2023-03-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
        migrations.AddField(
            model_name='product',
            name='classes_remaining',
            field=models.IntegerField(default=10, verbose_name='Nombre de cours restants'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_subscription',
            field=models.BooleanField(default=False, verbose_name='Abonnement'),
        ),
    ]
