# Generated by Django 4.1.1 on 2023-04-04 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_classes_remaining_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('classes_by_month', models.IntegerField(verbose_name='Nombre de cours par mois')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='UnitPass',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('remaining_classes', models.IntegerField(verbose_name='Nombre de cours restants')),
                ('date', models.DateField(verbose_name="Date d'achat")),
            ],
            bases=('products.product',),
        ),
    ]
