# Generated by Django 4.1.1 on 2023-04-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_subscription_unitpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitpass',
            name='remaining_classes',
            field=models.IntegerField(default=10, verbose_name='Nombre de cours restants'),
        ),
    ]
