# Generated by Django 4.1.1 on 2023-04-16 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('products', '0003_alter_product_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='contacts.contact', verbose_name='Élève'),
        ),
    ]
