# Generated by Django 4.1.1 on 2023-04-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_unitpass_remaining_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitpass',
            name='date',
        ),
    ]
