# Generated by Django 4.1.1 on 2023-04-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='recurrence',
            field=models.CharField(choices=[(1, 'Mensuel'), (2, 'Annuel')], max_length=100, verbose_name='Récurrence'),
        ),
    ]
