# Generated by Django 4.1.1 on 2023-04-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_subscription_recurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='recurrence',
            field=models.CharField(choices=[('M', 'Mensuel'), ('A', 'Annuel')], max_length=100, verbose_name='Récurrence'),
        ),
    ]
