# Generated by Django 4.1.1 on 2023-04-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_subscription_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='current_credits',
            field=models.IntegerField(default=1, verbose_name='Crédits restants'),
            preserve_default=False,
        ),
    ]
