# Generated by Django 4.1.1 on 2023-04-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_subscription_current_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='classes_by_week',
            field=models.IntegerField(default=1, verbose_name='Cours par semaine'),
        ),
    ]
