# Generated by Django 4.1.1 on 2023-04-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_subscription_classes_by_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='current_credits',
            field=models.IntegerField(default=0, verbose_name='Crédits restants'),
        ),
    ]
