# Generated by Django 3.1.4 on 2020-12-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(max_length=200, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='contact',
            name='lang',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Langue maternelle'),
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numéro de portable'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AddField(
            model_name='contact',
            name='region_zip',
            field=models.IntegerField(null=True, verbose_name='Code postale'),
        ),
        migrations.AddField(
            model_name='contact',
            name='street',
            field=models.CharField(max_length=100, null=True, verbose_name='Addresse'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='age',
            field=models.IntegerField(default=0, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nom et prénom du contact'),
        ),
    ]
