# Generated by Django 3.1.4 on 2020-12-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20201202_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.CharField(max_length=20, null=True, verbose_name='Etat'),
        ),
    ]
