# Generated by Django 3.1.3 on 2020-12-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20201201_1629'),
        ('contacts', '0003_contact_state'),
    ]

    operations = [
    ]
