# Generated by Django 3.1.6 on 2021-02-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20201202_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='lastname',
            field=models.CharField(max_length=200, null=True, verbose_name='Nom de famille'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lang',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Langue'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Prénom'),
        ),
    ]
