# Generated by Django 3.1.6 on 2021-02-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20210223_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
