# Generated by Django 3.1.6 on 2021-02-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20210224_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('FR', 'France'), ('CH', 'Suisse'), ('RU', 'Russia'), ('IT', 'Italy')], default='CH', max_length=100, verbose_name='Pays'),
        ),
    ]
