# Generated by Django 3.1.6 on 2021-02-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20210224_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='street',
            field=models.CharField(max_length=100, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(choices=[('M.', 'Monsieur'), ('Mme', 'Madame'), ('Melle', 'Mademoiselle'), ('NA', 'Sans avis')], default='Mme', max_length=50, verbose_name='titre'),
        ),
    ]
