# Generated by Django 3.1.6 on 2021-02-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom du produit')),
                ('price', models.FloatField(verbose_name='Prix du produit')),
            ],
        ),
    ]
