# Generated by Django 4.2 on 2023-05-02 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('title', models.CharField(choices=[('Mr', 'Mister'), ('Ms', 'Madame'), ('Miss', 'Miss')], default='Mme', max_length=50, verbose_name='titre')),
                ('name', models.CharField(max_length=200, verbose_name='Prénom')),
                ('lastname', models.CharField(max_length=200, verbose_name='Nom de famille')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresse')),
                ('region_zip', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code postale')),
                ('city', models.CharField(blank=True, max_length=60, null=True, verbose_name='Ville')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pays')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
