# Generated by Django 4.1.1 on 2022-09-19 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('title', models.CharField(choices=[('M.', 'Monsieur'), ('Mme', 'Madame'), ('Melle', 'Mademoiselle'), ('NA', 'Sans avis')], default='Mme', max_length=50, verbose_name='titre')),
                ('lang', models.CharField(choices=[('EN', 'Anglais'), ('FR', 'Francais'), ('CH', 'Suisse'), ('RU', 'Russe'), ('IT', 'Italien')], default='US', max_length=80, verbose_name='Langue')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Prénom')),
                ('lastname', models.CharField(max_length=200, null=True, verbose_name='Nom de famille')),
                ('age', models.IntegerField(null=True, verbose_name='Age')),
                ('street', models.CharField(max_length=100, null=True, verbose_name='Adresse')),
                ('region_zip', models.IntegerField(null=True, verbose_name='Code postale')),
                ('city', models.CharField(max_length=200, null=True, verbose_name='Ville')),
                ('country', models.CharField(choices=[('US', 'United States'), ('FR', 'France'), ('CH', 'Suisse'), ('RU', 'Russia'), ('IT', 'Italy')], default='CH', max_length=100, verbose_name='Pays')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('state', models.CharField(max_length=20, null=True, verbose_name='Etat')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
