# Generated by Django 4.1.1 on 2022-09-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='region_zip',
            field=models.CharField(max_length=50, verbose_name='Code postale'),
        ),
    ]
