# Generated by Django 4.1.1 on 2022-09-13 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorderline',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Products'),
        ),
    ]
