# Generated by Django 4.1.1 on 2022-09-29 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_region_zip'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='partner_id',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='contacts.contact', verbose_name='Customer'),
        ),
    ]
