# Generated by Django 4.1.1 on 2022-09-13 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('sale', '0002_alter_saleorderline_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='partner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.contact', verbose_name='Customer'),
        ),
    ]
