# Generated by Django 4.1.1 on 2022-09-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='street',
            field=models.CharField(default='Pierre-a-Sisier 11', max_length=100),
            preserve_default=False,
        ),
    ]
