# Generated by Django 3.1.6 on 2021-03-15 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('contacts', '0013_auto_20210226_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('validity_date', models.DateField(blank=True, null=True, verbose_name='Validity date')),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact', verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.FloatField(default=1, verbose_name='Quantity')),
                ('sol_total', models.FloatField(max_length=100, verbose_name='Total')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Products')),
                ('sale_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.saleorder')),
            ],
        ),
    ]
