# Generated by Django 3.1.6 on 2021-02-26 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0013_auto_20210226_1005'),
        ('products', '0009_product_tax_ids'),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validity_date', models.DateField(verbose_name='Validity date')),
                ('so_total', models.CharField(max_length=100, verbose_name='Total')),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact', verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.FloatField(default=1, verbose_name='Quantity')),
                ('price_unit', models.FloatField(verbose_name='Unit price')),
                ('sol_total', models.FloatField(max_length=100, verbose_name='Total')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Products')),
                ('sale_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.saleorder')),
                ('tax_id', models.ManyToManyField(to='tax.AccountTax', verbose_name='Tax')),
            ],
        ),
    ]
