# Generated by Django 3.1.6 on 2021-03-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
