# Generated by Django 3.1.6 on 2021-03-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorder',
            name='name',
        ),
    ]
