# Generated by Django 3.1.6 on 2021-03-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorderline',
            name='price_unit',
        ),
        migrations.AddField(
            model_name='saleorderline',
            name='ht_price',
            field=models.FloatField(default=0, verbose_name='HT price'),
            preserve_default=False,
        ),
    ]
