# Generated by Django 3.1.6 on 2021-03-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20210302_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleorderline',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleorderline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
