# Generated by Django 3.1.6 on 2021-03-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20210308_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='so_total',
            field=models.FloatField(blank=True, max_length=100, verbose_name='Total'),
        ),
    ]
