# Generated by Django 3.1.6 on 2021-03-06 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_remove_saleorder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
