# Generated by Django 3.1.6 on 2021-03-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20210309_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='so_total',
            field=models.FloatField(verbose_name='Total'),
        ),
    ]
