# Generated by Django 3.1.6 on 2021-03-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20210309_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='so_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Total'),
        ),
    ]
