# Generated by Django 3.1.6 on 2021-03-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20210309_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorder',
            name='so_total',
        ),
    ]
