# Generated by Django 3.1.6 on 2021-03-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_saleorder_validity_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorder',
            name='validity_date',
        ),
    ]
