# Generated by Django 3.1.6 on 2021-03-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_remove_saleorder_validity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='validity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Validity date'),
        ),
    ]
