# Generated by Django 3.1.6 on 2021-03-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_saleorder_validity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='so_total',
            field=models.CharField(blank=True, max_length=100, verbose_name='Total'),
        ),
    ]
