# Generated by Django 3.1.6 on 2021-03-03 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_auto_20210303_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
