# Generated by Django 4.1.1 on 2023-03-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classe_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='terminated',
            field=models.BooleanField(default=False, verbose_name='Terminated'),
        ),
    ]
