# Generated by Django 4.1.1 on 2023-04-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classe_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='session',
            name='schedule',
        ),
    ]
