# Generated by Django 4.1.1 on 2023-04-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('classe_sessions', '0002_remove_session_duration_remove_session_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='attendees',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, related_name='sessions', to='contacts.contact'),
        ),
    ]
