# Generated by Django 4.1.1 on 2023-04-07 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('products', '0005_remove_unitpass_date'),
        ('classe_sessions', '0003_alter_session_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='attendees',
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classe_sessions.session')),
            ],
        ),
    ]
