# Generated by Django 4.1.1 on 2023-04-07 13:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_unitpass_date'),
        ('contacts', '0001_initial'),
        ('classe_sessions', '0004_remove_session_attendees_presence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presence',
            old_name='session',
            new_name='session_id',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='user_id',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='presence',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='presence',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presence',
            name='uptated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='session',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='updtated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='attendee',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product'),
        ),
    ]
