# Generated by Django 3.1.6 on 2021-03-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nom du produit')),
                ('price', models.FloatField(verbose_name='Prix du produit')),
                ('description', models.TextField(null=True, verbose_name='Description du produit')),
                ('picture', models.ImageField(null=True, upload_to='products_url', verbose_name='Illustrations')),
            ],
        ),
    ]
