# Generated by Django 3.1.6 on 2021-02-19 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categ_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productcategory'),
        ),
    ]
