# Generated by Django 3.1.6 on 2021-02-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.ImageField(null=True, upload_to='products', verbose_name='Illustrations'),
        ),
    ]
