# Generated by Django 3.1.6 on 2021-02-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210219_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom de la taxe')),
                ('amount', models.FloatField(verbose_name='Valeur de la taxe')),
            ],
        ),
    ]
