# Generated by Django 3.1.6 on 2021-02-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_accounttax'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_ids',
            field=models.ManyToManyField(to='products.AccountTax'),
        ),
    ]
