# Generated by Django 3.1.6 on 2021-02-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_tax_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tax_ids',
        ),
        migrations.DeleteModel(
            name='AccountTax',
        ),
    ]
