# Generated by Django 3.1.6 on 2021-02-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
        ('products', '0008_auto_20210220_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_ids',
            field=models.ManyToManyField(to='tax.AccountTax'),
        ),
    ]
